# version: "3.8"

services:
  app:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11725605/yeonseoko:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
    restart: unless-stopped
